# -------------------------
# BASIC SERVICE CONFIG
# -------------------------
spring.application.name=user-ms
server.port=8081

# -------------------------
# EUREKA CONFIG
# -------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Optional (recommended for clarity in Eureka UI)
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true